[tool.poetry]
name = "voice-inpainting"
version = "0.1.0"
description = ""
authors = ["Philipp Seitz <phlippseitz@gmail.com>"]
readme = "README.md"

packages = [
    { include = "src" },
]

[tool.poetry.scripts]
streamlit-app = "src.main:main"

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
numpy = "<=1.26.4"
streamlit = "^1.40.2"
matplotlib = "^3.9.3"
watchdog = "^6.0.0"
torch = [
    { version = "^2.4.0+cu124", source = "pytorch-gpu", markers = "sys_platform != 'darwin'" },
    { url = "https://download.pytorch.org/whl/cpu/torch-2.4.0-cp312-none-macosx_11_0_arm64.whl", markers = "sys_platform == 'darwin'" }
]
ffmpeg-python = "^0.2.0"
llama-cpp-python = "^0.3.2"
huggingface-hub = "^0.26.3"
regex = "^2024.11.6"
safetensors = "^0.4.5"
transformers = "^4.46.3"
loguru = "^0.7.2"

[[tool.poetry.source]]
name = "pytorch-gpu"
url = "https://download.pytorch.org/whl/cu124"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
